apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: disable-pwa-cache
  namespace: goalixa-app
spec:
  headers:
    customResponseHeaders:
      Cache-Control: "no-store, no-cache, must-revalidate, max-age=0"
      Pragma: "no-cache"
      Expires: "0"
