apiVersion: v1
kind: Secret
metadata:
  name: goalixa-secrets
  namespace: goalixa-app
type: Opaque
stringData:
  SECRET_KEY: "spy0iH9YrpI5TESBrazL87Xr5uX/tM8J2ytGu9a8Vd0="
  AUTH_JWT_SECRET: "Mb2czY3HUqUwSIvQVQYEcbGaeDTFOeBeMrbr7M66CA0="
  GOOGLE_CLIENT_ID: "REPLACE_ME_GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "REPLACE_ME_GOOGLE_CLIENT_SECRET"
  ADMIN_EMAIL: "REPLACE_ME_ADMIN_EMAIL"
  ADMIN_PASSWORD: "REPLACE_ME_ADMIN_PASSWORD"
