apiVersion: apps/v1
kind: Deployment
metadata:
  name: goalixa
  namespace: goalixa-goalixa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goalixa
  template:
    metadata:
      labels:
        app: goalixa
    spec:
      containers:
        - name: goalixa
          image: REPLACE_ME_GOALIXA_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: REPLACE_ME_GOALIXA_CONTAINER_PORT
          envFrom:
            - configMapRef:
                name: goalixa-config
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: goalixa-secrets
                  key: APP_SECRET
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
