apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goalixa-ingress
  namespace: goalixa-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: app.goalixa.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goalixa
                port:
                  number: 80
