apiVersion: v1
kind: Secret
metadata:
  name: goalixa-secrets
  namespace: goalixa-app
type: Opaque
stringData:
  SECRET_KEY: "REPLACE_ME_SECRET_KEY"
  AUTH_JWT_SECRET: "REPLACE_ME_AUTH_JWT_SECRET"
  GOOGLE_CLIENT_ID: "REPLACE_ME_GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "REPLACE_ME_GOOGLE_CLIENT_SECRET"
  ADMIN_EMAIL: "REPLACE_ME_ADMIN_EMAIL"
  ADMIN_PASSWORD: "REPLACE_ME_ADMIN_PASSWORD"
